#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 19 14:32:09 2026

@author: marta.navarrobernad
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 16 12:06:38 2026

@author: marta.navarrobernad
"""

# -*- coding: utf-8 -*-
"""
(PCA-OBS)
- Detect R-peaks in ECG channel
- PCA-OBS (4 components) over 10k Hz signal
"""

from pathlib import Path
import mne
import numpy as np
from mne.preprocessing import apply_pca_obs
import gc

# configuration
BASE_DIR = Path("/home/marta.navarrobernad/Desktop/sub-P02/eeg")
# Buscamos los archivos que salieron de la re-referencia
INPUT_FILES = sorted(list(BASE_DIR.glob("*_Ref*.fif")))

OUT_DIR = BASE_DIR / "ESG_CLEAN_OBS"
OUT_DIR.mkdir(exist_ok=True)


# Channels to clean (Spinal + Peripheral)
CHANNELS_TO_CLEAN = [
    "Iz", "SC1", "S3", "S4", "S5", "S6", "S7", "S8", "S9",
    "S11", "S12", "S13", "S14", "S15", "S16", "S17", "S18", "S19", "SC6",
    "ENG_AXILLA", "ENG_ERB", 
    "AC", "TH6"
]

def main():
    if not INPUT_FILES:
        print(f" No se han encontrado archivos _Ref*.fif en {BASE_DIR}")
        return

    for f_path in INPUT_FILES:
        print(f"\n--- Ejecutando PCA-OBS: {f_path.name} ---")
        
        try:
            # A. Load re-referenced RAW data
            raw = mne.io.read_raw_fif(f_path, preload=True, verbose=False)
            
            # B. R-PEAK DETECTION
            print("  -> Buscando latidos en el canal ECG...")
            if 'ECG' not in raw.ch_names:
                print(f"  Error: No hay canal ECG en {f_path.name}. Saltando...")
                continue
            
            # Use a temporary resampled copy (1kHz) for faster detection
            raw_tmp = raw.copy().resample(1000, verbose=False)
            ecg_events, _, _ = mne.preprocessing.find_ecg_events(raw_tmp, ch_name='ECG', verbose=False)
            
            # Convert events to time (seconds)
            qrs_times = ecg_events[:, 0] / 1000.0
            print(f"  -> Se han detectado {len(qrs_times)} latidos.")
            
            del raw_tmp
            gc.collect()

            # C. APPLY PCA-OBS
            # Get indices for requested channels
            picks = [raw.ch_names.index(ch) for ch in CHANNELS_TO_CLEAN if ch in raw.ch_names]
            
            print("  -> Apliying PCA-OBS ...")
            raw_obs = apply_pca_obs(
                raw,
                qrs_times=qrs_times,
                picks=picks,
                n_components=4,
                verbose=False
            )
            
            # D. SAVE CLEAN DATA
            out_name = OUT_DIR / f"{f_path.stem}_OBS_Clean.fif"
            raw_obs.save(out_name, overwrite=True, verbose=False)
            print(f"  Guardado: {out_name.name}")
            
            # Clean memory
            del raw, raw_obs
            gc.collect()
            
        except Exception as e:
            print(f"  Error en {f_path.name}: {e}")

    print("\n PCA-OBS completado")

if __name__ == "__main__":
    main()
