#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 23 12:41:21 2026

@author: marta.navarrobernad
"""

# -*- coding: utf-8 -*-
# calculates adaptative thresholds for epoch rejection,depending on the filter applied
# 1. Filter, 2.Calculate threshold
import mne
import numpy as np
from pathlib import Path
import gc
import os

# configuration
os.environ['QT_QPA_PLATFORM'] = 'xcb'
BASE_DIR = Path("/home/marta.navarrobernad/Desktop/sub-P02/eeg")
INPUT_DIR = BASE_DIR / "EPOCHS_STAGING"
OUT_DIR = BASE_DIR / "CLEAN_EPOCHS_BENCHMARK"
REPORT_DIR = BASE_DIR / "REPORTS_CLEANING"

OUT_DIR.mkdir(exist_ok=True, parents=True)
REPORT_DIR.mkdir(exist_ok=True, parents=True)

# here we create different channel groups, because we dont want noisier channels such as erb and axilla contaminating esg rejection
# also we ignore reference channels (don't know if this is good or I should change it)
CH_ESG_BASE = ['Iz', 'SC1', 'SC6', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 
               'S11', 'S12', 'S13', 'S14', 'S15', 'S16', 'S17', 'S18', 'S19']
CH_ERB = ['ENG_ERB']
CH_AXI = ['ENG_AXILLA']
CH_REFS = ['AC', 'TH6']

# ddefine filters
def get_filter_defs():
    return {
        "Nierula_Std": {"l": 30, "h": 400, "order": 4, "type": "iir"},
        "Nierula_Late": {"l": 5, "h": 400, "order": 4, "type": "iir"},
        "Gabrieli": {"l": 50, "h": 800, "len":'auto', "type": "fir"},
        "Nierula_Otro": {"l": 1, "h": 400, "order": 2, "type": "iir"},
        "Mehra": {"l": 10, "h": 1500, "order": 2, "type": "iir"},
        "Wimmer": {"l": 0.5, "h": 60, "order": 3, "type": "iir_mixed"},
        "Boehme": {"l": 2, "h": 2000, "order": 4, "type": "iir"}
    }

# peak to peak amplitude for epoch, distance between highest and lowest point
# 98 percentil, we identify the value that leaves out the worse 2%
def get_thr(epochs, ch_type, minimum):
    data = epochs.copy().pick_types(**{ch_type: True}).get_data()
    if data.size == 0: return minimum
    p2ps = (np.max(data, axis=2) - np.min(data, axis=2)).max(axis=1) * 1e6
    return max(np.percentile(p2ps, 98), minimum)

def main():
    import pandas as pd
    from collections import Counter
    
    files = sorted(list(INPUT_DIR.glob("*-epo.fif")))
    filters = get_filter_defs()
    
    for f_path in files:
        print(f"\n Procesando archivo: {f_path.name}")
        epochs_orig = mne.read_epochs(f_path, preload=True, verbose=False)
        cleaning_summary = []

        for f_name, p in filters.items():
            print(f" Aplicando Filtro: {f_name}")
            ep_filt = epochs_orig.copy()
            
            # 1. Filter
            if p["type"] == "iir":
                ep_filt.filter(p["l"], p["h"], method='iir', 
                               iir_params=dict(order=p["order"], ftype='butter'), 
                               phase='zero', verbose=False)
            elif p["type"] == "fir":
                ep_filt.filter(p["l"], p["h"], method='fir', phase='zero', 
                               filter_length=p["len"], fir_design='firwin', verbose=False)
            elif p["type"] == "iir_mixed":
                ep_filt.filter(0.5, 60, method='iir', 
                               iir_params=dict(order=3, ftype='butter'), 
                               phase='zero', verbose=False)

            # 2. Channel config
            ep_filt.set_channel_types({ch: 'misc' for ch in ep_filt.ch_names}, verbose=False)
            for ch in CH_ESG_BASE:
                if ch in ep_filt.ch_names: ep_filt.set_channel_types({ch: 'eeg'}, verbose=False)
            if CH_ERB[0] in ep_filt.ch_names: ep_filt.set_channel_types({CH_ERB[0]: 'emg'}, verbose=False)
            if CH_AXI[0] in ep_filt.ch_names: ep_filt.set_channel_types({CH_AXI[0]: 'eog'}, verbose=False)

            # 3. Different TH for each group to stablish the rejection criteria
            t_esg = get_thr(ep_filt, 'eeg', 100)
            t_erb = get_thr(ep_filt, 'emg', 250)
            t_axi = get_thr(ep_filt, 'eog', 400)

            n_before = len(ep_filt)
            ep_filt.drop_bad(reject={'eeg': t_esg*1e-6, 'emg': t_erb*1e-6, 'eog': t_axi*1e-6}, verbose=False)
            n_after = len(ep_filt)
            
            # 4. Log of noisy channels
            drop_reasons = [ch for log in ep_filt.drop_log if log for ch in log]
            counts = Counter(drop_reasons)
            top_3_str = "; ".join([f"{ch}({n})" for ch, n in counts.most_common(3)])

            cleaning_summary.append({
                "filter_name": f_name,
                "total": n_before,
                "remaining": n_after,
                "rejected": n_before - n_after,
                "perc_rejected": round(((n_before - n_after) / n_before) * 100, 2),
                "thr_esg": round(t_esg, 2),
                "top_culprits": top_3_str
            })

            # 5. Save
            out_name = OUT_DIR / f"Clean_Epochs_{f_path.stem}_{f_name}-epo.fif"
            ep_filt.save(out_name, overwrite=True, verbose=False)
            
            print(f"      {f_name}: {n_after} epos. Top ruidosos: {top_3_str}")
            del ep_filt; gc.collect()

        # CSV
        df_summary = pd.DataFrame(cleaning_summary)
        csv_name = REPORT_DIR / f"Cleaning_Stats_{f_path.stem}.csv"
        df_summary.to_csv(csv_name, index=False)
        print(f"CSV GUARDADO: {csv_name.name}")
        
        del epochs_orig; gc.collect()

    print("\nLIMPIEZA COMPLETADA SIN REPORTS PESADOS")
    
if __name__ == "__main__":
    main()
