#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 24 13:49:32 2026

@author: marta.navarrobernad
"""

import mne
import os
import glob
import matplotlib.pyplot as plt

# Trigger config
# S = Standard, D = Deviant
TRIGGER_MAP = {
    'INATENTO': {
        'LOCAL':  {'S': [20, 21], 'D': [22, 23]},
        'GLOBAL': {'S': [20, 22], 'D': [21, 23]}
    },
    'ATENTO': {
        'LOCAL':  {'S': [10, 11], 'D': [12, 13]},
        'GLOBAL': {'S': [10, 12], 'D': [11, 13]}
    }
}

FILTROS = ["Nierula_Std", "Nierula_Late", "Gabrieli", "Nierula_Otro", "Mehra", "Wimmer", "Boehme"] #filters
REFERENCIAS = ["TH6"]  #ref, we can either put TH6 or AC depending on what we want to see
INPUT_PATH = "/home/marta.navarrobernad/Desktop/sub-P02/eeg/CLEAN_EPOCHS_BENCHMARK"

def run_averaging_pipeline():
    for ref in REFERENCIAS:
        root_avg_dir = f"averages_{ref}"
        
        for filtro in FILTROS:
            for estado in ['INATENTO', 'ATENTO']:
                # Define attentive or inattentive, the first 4 runs were inattentive 
                runs = range(1, 5) if estado == 'INATENTO' else range(5, 9)
                all_epochs_list = []
                
                for r in runs:
                    # Search last outputs
                    pattern = os.path.join(INPUT_PATH, f"Clean_Epochs_*Run{r}*Ref{ref}*{filtro}*-epo.fif")
                    files = glob.glob(pattern)
                    
                    if files:
                        epochs = mne.read_epochs(files[0], preload=True, verbose=False)
                        # events id
                        new_event_id = {str(val): val for val in epochs.events[:, 2]}
                        epochs.event_id = new_event_id
                        all_epochs_list.append(epochs)
                
                if not all_epochs_list:
                    continue
                
                # Concatenate for runs for condition attentive and other for for inattentive
                combined_epochs = mne.concatenate_epochs(all_epochs_list, verbose=False)
                
                for tipo in ['LOCAL', 'GLOBAL']:
                    target_dir = os.path.join(root_avg_dir, estado, tipo)
                    os.makedirs(target_dir, exist_ok=True)
                    
                    # Extract IDs
                    ids_s = [str(i) for i in TRIGGER_MAP[estado][tipo]['S']]
                    ids_d = [str(i) for i in TRIGGER_MAP[estado][tipo]['D']]
                    
                    present_ids = combined_epochs.event_id.keys()
                    valid_s = [i for i in ids_s if i in present_ids]
                    valid_d = [i for i in ids_d if i in present_ids]
                    
                    evokeds_dict = {}
                    if valid_s:
                        ev_s = combined_epochs[valid_s].average()
                        ev_s.comment = 'Standard'
                        evokeds_dict['Standard'] = ev_s
                        
                    if valid_d:
                        ev_d = combined_epochs[valid_d].average()
                        ev_d.comment = 'Deviant'
                        evokeds_dict['Deviant'] = ev_d
                    
                    if evokeds_dict:
                        # 1. Save
                        output_filename = f"Avg_{filtro}_{ref}_{estado}_{tipo}"
                        output_path_fif = os.path.join(target_dir, f"{output_filename}-ave.fif")
                        mne.write_evokeds(output_path_fif, list(evokeds_dict.values()), overwrite=True, verbose=False)
                        
                        # 2. Comparision graphic
                        try:
                            fig = mne.viz.plot_compare_evokeds(
                                evokeds_dict, 
                                picks='eeg', 
                                title=f"{filtro} {ref} {estado} {tipo}",
                                show=False
                            )
                            if isinstance(fig, list):
                                fig = fig[0]
                            
                            output_path_png = os.path.join(target_dir, f"{output_filename}.png")
                            fig.savefig(output_path_png)
                            plt.close(fig)
                        except Exception as e:
                            print(f"No se pudo generar el gráfico para {output_filename}: {e}")

                        print(f"Procesado: {output_filename}")

if __name__ == "__main__":
    run_averaging_pipeline()
